const banco = [
    { palabra: 'css', dificultad: 'facil' },
    { palabra: 'git', dificultad: 'facil' },
    { palabra: 'html', dificultad: 'facil' },
    { palabra: 'json', dificultad: 'facil' },
    { palabra: 'node', dificultad: 'facil' },
    { palabra: 'vite', dificultad: 'facil' },
    { palabra: 'react', dificultad: 'medio' },
    { palabra: 'array', dificultad: 'medio' },
    { palabra: 'clase', dificultad: 'medio' },
    { palabra: 'objeto', dificultad: 'medio' },
    { palabra: 'funcion', dificultad: 'medio' },
    { palabra: 'variable', dificultad: 'medio' },
    { palabra: 'servidor', dificultad: 'medio' },
    { palabra: 'navegador', dificultad: 'dificil' },
    { palabra: 'framework', dificultad: 'dificil' },
    { palabra: 'algoritmo', dificultad: 'dificil' },
    { palabra: 'javascript', dificultad: 'dificil' },
    { palabra: 'asincronia', dificultad: 'dificil' },
    { palabra: 'recursividad', dificultad: 'dificil' },
    { palabra: 'paradojaexistencial', dificultad: 'dificil' },
];

const partesAhorcado = [
    'parte-cabeza',
    'parte-cuerpo',
    'parte-brazo-izq',
    'parte-brazo-der',
    'parte-pierna-izq',
    'parte-pierna-der',
];